version: "3"

services:
  strapi:
    image: m2strapi:4.0.7
    container_name: strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - strapi-app-network
    volumes:
      - ./app:/srv/app
    ports:
      - "1337:1337"

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DATABASE_NAME}"
      MYSQL_USER: "${DATABASE_USERNAME}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
    networks:
      - strapi-app-network
    volumes:
      - ./db/data:/var/lib/mysql/data
      - ./db/logs:/var/lib/mysql/logs
      - /var/docker/mariadb/conf:/etc/mysql
    ports:
      - "3306:3306"

networks:
  strapi-app-network:
    driver: bridge

volumes:
  strapidata:
